device: cuda
embedding_net:
  args:
    input_channel: 1
    output_dim: 128
  class: ConvNet
  module: CNN
model:
  backend: sbi
  engine: NPE
  name: toy_NPE
  nets:
  - hidden_features: 70
    model: nsf
    num_transforms: 10
    signature: m1
  - hidden_features: 70
    model: nsf
    num_transforms: 10
    signature: m2
  - hidden_features: 70
    model: nsf
    num_transforms: 10
    signature: m3
  - hidden_features: 70
    model: nsf
    num_transforms: 10
    signature: m4
out_dir: ./
prior:
  args:
    high:
    - 100.0
    low:
    - 2.0
  class: Uniform
  module: ili.utils
train_args:
  learning_rate: 0.0001
  stop_after_epochs: 20
  training_batch_size: 2048
  validation_fraction: 0.2
