device: cuda
embedding_net:
  args:
    output_dim: 10
  class: ConvNet
  module: CNN
model:
  backend: lampe
  engine: NPE
  name: toy_NPE
  nets:
  - hidden_features: 70
    model: gf
    num_transforms: 5
    signature: m1
out_dir: ./
prior:
  args:
    high:
    - 9.778040286463124
    - 1.1407118802345704
    low:
    - 4.4.711969898733544
    - -0.34796754710159744
  class: Uniform
  module: ili.utils
train_args:
  learning_rate: 1.0e-05
  stop_after_epochs: 20
  training_batch_size: 1024
  validation_fraction: 0.1
